/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.group7.nomnom;

/**
 *
 * @author mc4ev
 */
public class Courier extends User {
    public Courier(int id, String name, String username, String password) {
        super(id, name, username, password);
    }

    public void menu() {
        // GUI
        System.out.println("Courier Menu:");
        System.out.println("1. View Deliveries");
        System.out.println("2. Update Status");
        System.out.println("3. Logout");
    }
    
    // Pending Task Class
    public void viewDeliveryTasks() {
        System.out.println("Delivery Tasks");
        // delivery task should be generated by vendor after they accept a delivery order
        
        // read orders with type delivery and pending courier status
    }
    
    public void acceptDeliveryTask(int task_id){
        System.out.println("Delivery Tasks");
    }
    
    public void declineDeliveryTask(int task_id){
        System.out.println("Delivery Tasks");
    }
    
    public void updateTaskStatus(int task_id, String new_status){
        System.out.println("Delivery Tasks");
        // Case 1: when the order is taken from vendor
        // Case 2: when the order is dropped off
    }
    
    // Pending Task Class
    public void viewTaskHistory(String filter_period){
        System.out.println("Delivery Tasks");
        
        // view all "delivered" tasks (task.courier_id = current ? task.order_id | order.status = delivered ? VIEW)
    }
    
    public float viewEarnings(String filterPeriod){
        System.out.println("Delivery Tasks");
        return 0;
        
        // sum of delivery charges of orders (task.courier_id = current ? task.order_id | order.delivery_charge)
    }
    
    // Pending Review Class
    public void readCustomerReviews(){
        System.out.println("Delivery Tasks");
        // review should be generated by customer
        
        // read reviews (task.courier_id = current ? task.order_id | order.review_message)
    }
}
