/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonNull;
import com.google.gson.JsonObject;
import com.group7.nomnom.Courier;
import com.group7.nomnom.DeliveryTask;
import com.group7.nomnom.FileHandler;
import com.group7.nomnom.User;
import static com.group7.nomnom.User.updatePassword;
import com.group7.nomnom.Utils;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Comparator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author mc4ev
 */
public class courier_page extends javax.swing.JFrame {

    // Initialize GSON
    private static final Gson gson = new Gson();

    // Declare the courier instance variable
    private Courier courier;

    /**
     * Creates new form courier_page
     * 
     * @param user
     */
    public courier_page(User user) {
        initComponents();
        courierTabs.setSelectedIndex(0);

        profileUserName.setText(user.getName());
        homeUserName.setText(user.getName());
        courier = new Courier(user.getId(), user.getName(), user.getUsername(), "", false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        currentPassword = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        NewPassword = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        repeatPassword = new javax.swing.JPasswordField();
        jButton5 = new javax.swing.JButton();
        container = new javax.swing.JPanel();
        imagePanel = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        topPanel = new javax.swing.JPanel();
        sidebarPanel = new javax.swing.JPanel();
        openDashboardBtn = new javax.swing.JButton();
        showTasksHistoryBtn = new javax.swing.JButton();
        profileUserRole = new javax.swing.JLabel();
        profileUserName = new javax.swing.JLabel();
        profileUserPicture = new javax.swing.JLabel();
        profilePanel = new javax.swing.JPanel();
        showEarningsBtn = new javax.swing.JButton();
        courierTabs = new javax.swing.JTabbedPane();
        courierDashboard1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        homeUserName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        currentDate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        newTasksTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        currentTasksTable = new javax.swing.JTable();
        acceptButton = new javax.swing.JButton();
        pickupButton = new javax.swing.JButton();
        deliveryButton = new javax.swing.JButton();
        tasksHistoryTab = new javax.swing.JPanel();
        searchButton = new javax.swing.JButton();
        completedOrderFilter = new javax.swing.JComboBox<>();
        searchField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        historyTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        earningsTab = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        timeFilterComboBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        earningsTable = new javax.swing.JTable();
        totalAmountLabel = new javax.swing.JLabel();
        averagePerMonthLabel = new javax.swing.JLabel();
        tasksCompletedLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        profileTab = new javax.swing.JPanel();
        logUserOut = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        currentUserPassword = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        enteredNewPassword = new javax.swing.JPasswordField();
        jLabel17 = new javax.swing.JLabel();
        enteredConfirmPassword = new javax.swing.JPasswordField();
        updatePassword = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        userPicture = new javax.swing.JLabel();
        userProfile = new javax.swing.JLabel();

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Update the password");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("current password");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("New password");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("repeat password");

        jButton5.setText("UPDATE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        container.setBackground(new java.awt.Color(255, 255, 255));
        container.setPreferredSize(new java.awt.Dimension(900, 660));
        container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagePanel.setPreferredSize(new java.awt.Dimension(202, 178));

        imageLabel.setIcon(new javax.swing.ImageIcon("/Users/mqaid/Documents/NomNom-oms/src/main/java/assets/login logo.png")); // NOI18N
        imageLabel.setText("jLabel1");

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanelLayout.createSequentialGroup()
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanelLayout.createSequentialGroup()
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        container.add(imagePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        topPanel.setBackground(new java.awt.Color(255, 96, 31));
        topPanel.setPreferredSize(new java.awt.Dimension(748, 67));

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );

        container.add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 700, -1));

        sidebarPanel.setBackground(new java.awt.Color(255, 224, 200));

        openDashboardBtn.setForeground(new java.awt.Color(255, 96, 31));
        openDashboardBtn.setText("Dashboard");
        openDashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openDashboardBtnActionPerformed(evt);
            }
        });

        showTasksHistoryBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        showTasksHistoryBtn.setForeground(new java.awt.Color(255, 96, 31));
        showTasksHistoryBtn.setText("Tasks History");
        showTasksHistoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTasksHistoryBtnActionPerformed(evt);
            }
        });

        profileUserRole.setForeground(new java.awt.Color(153, 153, 153));
        profileUserRole.setText("Courier");

        profileUserName.setForeground(new java.awt.Color(255, 96, 31));

        profileUserPicture.setIcon(new javax.swing.ImageIcon("/Users/mqaid/Documents/NomNom-oms/src/main/java/assets/user-profile.jpg")); // NOI18N

        profilePanel.setBackground(new java.awt.Color(255, 255, 255));
        profilePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profilePanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        showEarningsBtn.setForeground(new java.awt.Color(255, 96, 31));
        showEarningsBtn.setText("Earnings");
        showEarningsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showEarningsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(openDashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(showTasksHistoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(showEarningsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(profileUserPicture)
                        .addGap(10, 10, 10)
                        .addComponent(profileUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(profileUserRole, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(profilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(openDashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(showTasksHistoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(showEarningsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(profileUserPicture))
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(profileUserRole, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(profilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(profileUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        container.add(sidebarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 200, 480));

        courierTabs.setBackground(new java.awt.Color(255, 255, 255));

        courierDashboard1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("Welcome,");

        homeUserName.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        homeUserName.setForeground(new java.awt.Color(255, 102, 51));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel3.setText("Your Current Tasks:");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel4.setText("Available Tasks:");

        jLabel5.setText("Day:");

        newTasksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Restaurant", "Ordered By", "Location", "Time", "Amount"
            }
        ));
        jScrollPane1.setViewportView(newTasksTable);

        currentTasksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Restaurant", "Ordered By", "Location", "Status"
            }
        ));
        jScrollPane2.setViewportView(currentTasksTable);

        acceptButton.setText("ACCEPT");
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });

        pickupButton.setText("PICK UP");
        pickupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickupButtonActionPerformed(evt);
            }
        });

        deliveryButton.setText("DELIVERED");
        deliveryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout courierDashboard1Layout = new javax.swing.GroupLayout(courierDashboard1);
        courierDashboard1.setLayout(courierDashboard1Layout);
        courierDashboard1Layout.setHorizontalGroup(
            courierDashboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(courierDashboard1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(courierDashboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(courierDashboard1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(courierDashboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(courierDashboard1Layout.createSequentialGroup()
                                .addComponent(pickupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deliveryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)))
                    .addGroup(courierDashboard1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(currentDate)
                        .addGap(18, 18, 18))
                    .addGroup(courierDashboard1Layout.createSequentialGroup()
                        .addGroup(courierDashboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(homeUserName)
                            .addComponent(jLabel4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(courierDashboard1Layout.createSequentialGroup()
                        .addGroup(courierDashboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(acceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        courierDashboard1Layout.setVerticalGroup(
            courierDashboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(courierDashboard1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(courierDashboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(courierDashboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(currentDate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeUserName)
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(courierDashboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deliveryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pickupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(acceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        courierTabs.addTab("Run a Task", courierDashboard1);

        tasksHistoryTab.setBackground(new java.awt.Color(255, 255, 255));

        searchButton.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        searchButton.setText("search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        completedOrderFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "1M", "6M", "12M" }));
        completedOrderFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completedOrderFilterActionPerformed(evt);
            }
        });

        searchField.setForeground(new java.awt.Color(204, 204, 204));
        searchField.setText("Restaurant Name");
        searchField.setBorder(javax.swing.BorderFactory.createTitledBorder("search bar"));
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        jLabel12.setText("Filter by Date:");

        historyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Restaurant", "Ordered By", "Location", "Date", "Amount"
            }
        ));
        jScrollPane3.setViewportView(historyTable);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setText("Tasks History");

        javax.swing.GroupLayout tasksHistoryTabLayout = new javax.swing.GroupLayout(tasksHistoryTab);
        tasksHistoryTab.setLayout(tasksHistoryTabLayout);
        tasksHistoryTabLayout.setHorizontalGroup(
            tasksHistoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tasksHistoryTabLayout.createSequentialGroup()
                .addGroup(tasksHistoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tasksHistoryTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addGroup(tasksHistoryTabLayout.createSequentialGroup()
                        .addGroup(tasksHistoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tasksHistoryTabLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel2))
                            .addGroup(tasksHistoryTabLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(searchButton)
                                .addGap(18, 18, 18)
                                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(completedOrderFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tasksHistoryTabLayout.setVerticalGroup(
            tasksHistoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tasksHistoryTabLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addGroup(tasksHistoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton)
                    .addGroup(tasksHistoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(completedOrderFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        courierTabs.addTab("History", tasksHistoryTab);

        earningsTab.setBackground(new java.awt.Color(255, 255, 255));

        label.setText("Total Amount Collected:");

        jLabel7.setText("Number of Task Completed:");

        label2.setText("Average Per Month:");

        timeFilterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "1M", "6M", "12M" }));
        timeFilterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeFilterComboBoxActionPerformed(evt);
            }
        });

        jLabel11.setText("Filter by Date:");

        earningsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Restaurant ", "Date", "Amount"
            }
        ));
        jScrollPane4.setViewportView(earningsTable);

        totalAmountLabel.setText("total  ");

        averagePerMonthLabel.setText("average");

        tasksCompletedLabel.setText("number of task");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel6.setText("Earnings");

        javax.swing.GroupLayout earningsTabLayout = new javax.swing.GroupLayout(earningsTab);
        earningsTab.setLayout(earningsTabLayout);
        earningsTabLayout.setHorizontalGroup(
            earningsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(earningsTabLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(earningsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(earningsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7)
                        .addComponent(label2)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, earningsTabLayout.createSequentialGroup()
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(timeFilterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(label))
                    .addGroup(earningsTabLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(earningsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(totalAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(averagePerMonthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tasksCompletedLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(earningsTabLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        earningsTabLayout.setVerticalGroup(
            earningsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(earningsTabLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6)
                .addGroup(earningsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(earningsTabLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(earningsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timeFilterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(43, 43, 43)
                        .addComponent(label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalAmountLabel)
                        .addGap(23, 23, 23)
                        .addComponent(label2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(averagePerMonthLabel)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tasksCompletedLabel))
                    .addGroup(earningsTabLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        courierTabs.addTab("Earnings", earningsTab);

        logUserOut.setText("Log out");
        logUserOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logUserOutActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Change the password");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Current Password:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("New Password:");

        enteredNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enteredNewPasswordActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Confirm Password:");

        enteredConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enteredConfirmPasswordActionPerformed(evt);
            }
        });

        updatePassword.setText("Update");
        updatePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePasswordActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("Profile");

        userPicture.setIcon(new javax.swing.ImageIcon("/Users/mqaid/Documents/NomNom-oms/src/main/java/assets/user-profile-large.jpg")); // NOI18N

        javax.swing.GroupLayout profileTabLayout = new javax.swing.GroupLayout(profileTab);
        profileTab.setLayout(profileTabLayout);
        profileTabLayout.setHorizontalGroup(
            profileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileTabLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(profileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, profileTabLayout.createSequentialGroup()
                        .addComponent(userPicture)
                        .addGap(18, 18, 18)
                        .addComponent(userProfile)
                        .addGap(76, 76, 76)
                        .addComponent(logUserOut))
                    .addGroup(profileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel18)
                        .addComponent(updatePassword)
                        .addComponent(jLabel14)
                        .addGroup(profileTabLayout.createSequentialGroup()
                            .addGroup(profileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(profileTabLayout.createSequentialGroup()
                                    .addGroup(profileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel15))
                                    .addGap(59, 59, 59))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profileTabLayout.createSequentialGroup()
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                            .addGroup(profileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(currentUserPassword)
                                .addComponent(enteredNewPassword)
                                .addComponent(enteredConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(332, Short.MAX_VALUE))
        );
        profileTabLayout.setVerticalGroup(
            profileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileTabLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel18)
                .addGroup(profileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profileTabLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userPicture))
                    .addGroup(profileTabLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(profileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logUserOut)
                            .addComponent(userProfile))))
                .addGap(29, 29, 29)
                .addComponent(jLabel14)
                .addGap(20, 20, 20)
                .addGroup(profileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enteredNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enteredConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(29, 29, 29)
                .addComponent(updatePassword)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        courierTabs.addTab("Profile", profileTab);

        container.add(courierTabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 700, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(932, 721));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void openDashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_openDashboardBtnActionPerformed

        loadCurrentTasks();
        loadNewTasks();

        Date currentDateObject = new Date();
        currentDate.setText(Utils.extractDate(currentDateObject.toString()));

    }// GEN-LAST:event_openDashboardBtnActionPerformed

    private void showTasksHistoryBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_showTasksHistoryBtnActionPerformed
        courierTabs.setSelectedIndex(1);
        historyTable.setModel(courier.getDeliveryHistoryTableModel());
    }// GEN-LAST:event_showTasksHistoryBtnActionPerformed

    private void showEarningsBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_showEarningsBtnActionPerformed

        courierTabs.setSelectedIndex(2); // Switch to earnings tab if needed
        String selectedFilter = timeFilterComboBox.getSelectedItem().toString();
        loadEarningsTable(selectedFilter);

    }// GEN-LAST:event_showEarningsBtnActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ActionPerformed

    }// GEN-LAST:event_jButton5ActionPerformed

    private void updatePasswordActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_updatePasswordActionPerformed

        String username = courier.getUsername();
        String currentPassword = currentUserPassword.getText();
        String newPassword = enteredNewPassword.getText();
        String confirmPassword = enteredConfirmPassword.getText();

        updatePassword(username, currentPassword, newPassword, confirmPassword);
        currentUserPassword.setText("");
        enteredNewPassword.setText("");
        enteredConfirmPassword.setText("");
    }// GEN-LAST:event_updatePasswordActionPerformed

    private void logUserOutActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_logUserOutActionPerformed

        // Close the current window
        this.dispose();

        // Open the Login screen
        login_page login = new login_page();
        login.setVisible(true);

    }// GEN-LAST:event_logUserOutActionPerformed

    private void timeFilterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_timeFilterComboBoxActionPerformed

        timeFilterComboBox.addActionListener(e -> {
            String selectedFilter = timeFilterComboBox.getSelectedItem().toString();
            loadEarningsTable(selectedFilter);
        });
    }// GEN-LAST:event_timeFilterComboBoxActionPerformed

    private void completedOrderFilterActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_completedOrderFilterActionPerformed

        String selectedOption = completedOrderFilter.getSelectedItem().toString();
        DefaultTableModel model = (DefaultTableModel) historyTable.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        historyTable.setRowSorter(sorter);

        // Get current date
        LocalDate currentDate = LocalDate.now();
        LocalDate filterDate = null;

        // Determine the date threshold based on selection
        switch (selectedOption) {
            case "1M":
                filterDate = currentDate.minusMonths(1);
                break;
            case "6M":
                filterDate = currentDate.minusMonths(6);
                break;
            case "12M":
                filterDate = currentDate.minusMonths(12);
                break;
            case "All":
            default:
                sorter.setRowFilter(null); // Show all data
                return;
        }

        // Apply date filter
        LocalDate finalFilterDate = filterDate;
        sorter.setRowFilter(new RowFilter<DefaultTableModel, Integer>() {
            @Override
            public boolean include(RowFilter.Entry<? extends DefaultTableModel, ? extends Integer> entry) {
                String dateStr = entry.getStringValue(4); // Column index for "Date" (yyyy-MM-dd)
                try {
                    LocalDate rowDate = LocalDate.parse(dateStr);
                    return !rowDate.isBefore(finalFilterDate); // Show only rows within the selected range
                } catch (Exception e) {
                    return false; // Skip rows with invalid date format
                }
            }
        });

    }// GEN-LAST:event_completedOrderFilterActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_searchButtonActionPerformed

        String searchText = searchField.getText().trim().toLowerCase();

        DefaultTableModel model = (DefaultTableModel) historyTable.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        historyTable.setRowSorter(sorter);

        if (searchText.isEmpty()) {
            sorter.setRowFilter(null); // Show all rows if search is empty
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + searchText, 1, 2, 3));
            // Columns: 1 -> Restaurant, 2 -> Ordered By, 3 -> Location
        }

    }// GEN-LAST:event_searchButtonActionPerformed

    private void deliveryButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deliveryButtonActionPerformed

        int selectedRow = currentTasksTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a task first!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int orderId = Integer.parseInt(currentTasksTable.getValueAt(selectedRow, 0).toString());
        courier.updateTaskStatus(orderId, "DELIVERED", "date_delivered");
        loadCurrentTasks();
        JOptionPane.showMessageDialog(this, "Order delivered successfully!", "Success",
                JOptionPane.INFORMATION_MESSAGE);

    }// GEN-LAST:event_deliveryButtonActionPerformed

    private void pickupButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pickupButtonActionPerformed

        int selectedRow = currentTasksTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a task first!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int orderId = Integer.parseInt(currentTasksTable.getValueAt(selectedRow, 0).toString());
        courier.updateTaskStatus(orderId, "OUT_FOR_DELIVERY", "date_picked");
        loadCurrentTasks();
        JOptionPane.showMessageDialog(this, "Order picked up successfully!", "Success",
                JOptionPane.INFORMATION_MESSAGE);
    }// GEN-LAST:event_pickupButtonActionPerformed

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_acceptButtonActionPerformed

        int selectedRow = newTasksTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select an order first!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int orderId = (int) newTasksTable.getValueAt(selectedRow, 0);
        courier.acceptDeliveryTask(orderId);
        loadNewTasks();
        loadCurrentTasks();
        JOptionPane.showMessageDialog(this, "Order has been accepted", "Success", JOptionPane.INFORMATION_MESSAGE);

    }// GEN-LAST:event_acceptButtonActionPerformed

    private void profilePanelMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_profilePanelMouseClicked
        courierTabs.setSelectedIndex(3);
        userPicture.setText(courier.getName());
    }// GEN-LAST:event_profilePanelMouseClicked

    private void enteredNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_enteredNewPasswordActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_enteredNewPasswordActionPerformed

    private void enteredConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_enteredConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_enteredConfirmPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(courier_page.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(courier_page.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(courier_page.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(courier_page.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField NewPassword;
    private javax.swing.JButton acceptButton;
    private javax.swing.JLabel averagePerMonthLabel;
    private javax.swing.JComboBox<String> completedOrderFilter;
    private javax.swing.JPanel container;
    private javax.swing.JPanel courierDashboard1;
    private javax.swing.JTabbedPane courierTabs;
    private javax.swing.JLabel currentDate;
    private javax.swing.JPasswordField currentPassword;
    private javax.swing.JTable currentTasksTable;
    private javax.swing.JPasswordField currentUserPassword;
    private javax.swing.JButton deliveryButton;
    private javax.swing.JPanel earningsTab;
    private javax.swing.JTable earningsTable;
    private javax.swing.JPasswordField enteredConfirmPassword;
    private javax.swing.JPasswordField enteredNewPassword;
    private javax.swing.JTable historyTable;
    private javax.swing.JLabel homeUserName;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label2;
    private javax.swing.JButton logUserOut;
    private javax.swing.JTable newTasksTable;
    private javax.swing.JButton openDashboardBtn;
    private javax.swing.JButton pickupButton;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JPanel profileTab;
    private javax.swing.JLabel profileUserName;
    private javax.swing.JLabel profileUserPicture;
    private javax.swing.JLabel profileUserRole;
    private javax.swing.JPasswordField repeatPassword;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton showEarningsBtn;
    private javax.swing.JButton showTasksHistoryBtn;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JLabel tasksCompletedLabel;
    private javax.swing.JPanel tasksHistoryTab;
    private javax.swing.JComboBox<String> timeFilterComboBox;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel totalAmountLabel;
    private javax.swing.JButton updatePassword;
    private javax.swing.JLabel userPicture;
    private javax.swing.JLabel userProfile;
    // End of variables declaration//GEN-END:variables

    private void loadNewTasks() {
        newTasksTable.setModel(courier.getNewTasksTableModel());
    }

    private void loadCurrentTasks() {
        currentTasksTable.setModel(courier.getCurrentTasksTableModel());
    }

    private void loadEarningsTable(String timeFilter) {
        courier.loadEarningsTable((DefaultTableModel) earningsTable.getModel(), totalAmountLabel, averagePerMonthLabel, tasksCompletedLabel, timeFilter);
    }

}
